### PR TITLE
mk_sdcard_image: Make a wider assumption of a DomD rootfs file type

### PR DESCRIPTION
**Pull request by aanisov**
Signed-off-by: Andrii Anisov <andrii_anisov@epam.com>

### CODE REVIEW

**Comment by andr2000** [comment]
can it be that besides .xz there could be other files with the same base name and different extensions which will fall in the "*rootfs.tar.*" mask?

**Comment by aanisov** [comment]
in the prod-devel-next the image is tar.bz2, also tar.gz is also supported by yocto

**Comment by aanisov** [comment]
From TI times, I remember they generated both *rootfs.tar.gz and *rootfs.tar.bz2. Its odd, but it exists. And only the first one should be taken. But I don't think yocto will generate some image which is not a rootfs but named \*rootfs.tar.\*.

**Comment by andr2000** [comment]
I was more concerned if there is a chance we have "root.tar.temp" or some other temporary files matching the mask

**Comment by aanisov** [comment]
Well, I'm not aware of such files produced by yocto.

**Comment by andr2000** [comment]
ok then

**Pull request merged**
